### PR TITLE
- Updated the mod to work with minecraft 1.19.2 + some configuration changes

### PR DESCRIPTION
**Pull request by mooviies**
- Changed how the configuration works to specify which spawn events are prevented
- Merged mod/mob list together to simplify Configuration
- Added default configuration for vanilla mobs and multiple modded mobs.

### CODE REVIEW

**Comment by mooviies** [comment]
I tested it on my Valhelsia 5 server and everything seems to work well!

**Comment by EverettSummer** [comment]
Sorry, I didn't notice this PR. I haven't played Minecraft for a year. I see you change the build-related files a lot, like grade, Is this required by 1.19 MDK?

**Comment by mooviies** [comment]
Hey! I was having trouble compiling it so I looked at the mdk 1.19 files to change the gradle build file and that made it work.

**Comment by EverettSummer** [comment]
Great! Thank you for your contribution.

**Pull request merged**
